### ISSUE TITLE
Publish event when phone call is completed

### ISSUE THREAD

**Issue by subbu** [subbu/staffagent_py#2]
When a phone call is completed by Twilio, send a webhook to Phoenix project. Include other life-cycle events as well for phone calls. This being handled in the finally block of websocket_handler(websocket: WebSocket, call_id: str) in server.py.

**Comment by phoenix1406** [comment]
>

**Comment by phoenix1406** [comment]
Added the logic for the event to track the status of the  phone call  that will act as. a  triggering identity
